name: Tests & QA

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ "8.0", "8.1", "8.2", "8.3", "8.4" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-suggest --no-interaction

      - name: phpstan
        run: vendor/bin/phpstan analyse -c phpstan.neon

      - name: psalm
        run: vendor/bin/psalm

      - name: Run Tests
        run: vendor/bin/phpunit --testdox